services:
  django:
    image: kidfromjupiter/personal:portals-backend
    ports:
      - "4001:4001"
    environment:
      DJANGO_SETTINGS_MODULE: portalsDjango.settings.dev
    restart: unless-stopped

  nextjs:
    image: kidfromjupiter/personal:portals-frontend
    ports:
      - "4000:4000"
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

