services:
  django:
    image: kidfromjupiter/portfolio:portals-backend
    ports:
      - "4001:4001"
    environment:
      DJANGO_SETTINGS_MODULE: portalsDjango.settings.dev

  nextjs:
    image: kidfromjupiter/portfolio:portals-frontend
    ports:
      - "4000:4000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

